scribble/config/routes.rb
Rails.application.routes.draw do
  
  root to: "posts#index"
  resources :posts do
resources :comments
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

scribble/app/models/article.rb
class Article < ApplicationRecord
  has_many :songs, dependent: :destroy
end

scribble/app/models/authorization.rb
class Authorization
  belongs_to :user
  validates :provider, :uid, :presence => true
end

scribble/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tags
  belongs_to :post
end

scribble/app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :posts
  has_many :authorizations
  validates :name, :email, :presence => true
end

scribble/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.create!(artist_params)

    redirect_to artist_path(@category)
  end

  def update
    @category = Category
  end

  def destroy
    @category = Category
  end

end

scribble/app/controllers/comment_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:artist_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

end

scribble/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def edit
  end

  def delete
  end
end

scribble/app/controllers/concerns/posts_controller.rb
class PostsController < ApplicationController
def index
  @posts = Post.all
end

def show
  @post = Post.find(params[:id])
end

def new
  @post = Post.new
end

def create

  @post = Post.create! post_params
  redirect_to "/posts/#{@post.id}"
end

private
def post_params
  params.require(:post).permit(:title, :body)
end

end

scribble/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_posts = Post.all.order(:created_at).limit(3)
  end
end

scribble/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def delete
  end

  def show
    @post = Post.find(params[:id])
  end

end

scribble/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    redirect_to posts_url
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

scribble/app/helpers/pages_helper.rb
module PagesHelper
end

scribble/app/helpers/scribbler_helper.rb
module ScribblerHelper
end

scribble/app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

scribble/app/views/comments/_comment.html.erb
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

scribble/app/views/comments/_comments.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

scribble/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

scribble/app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

scribble/app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

scribble/app/views/comments/index.html.erb
<% @comments.each do |comment| %>

  <li><%=link_to comment.userName, post_comment_path(@post, comment) %></li>

<%end%>

<%=link_to "click here to go back to home page", root_path %>

scribble/app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

scribble/app/views/comments/show.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :user_name %>
  <%= f.text_field :userName %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <!-- How can I change it to show update_at if it was updated? -->
  <%= f.label :created_at %>
  <%= f.text_field :created_at %>
  <%= f.submit  %>
<%end%>

scribble/app/views/home/index.html.erb
<h1>RECENT POSTS</h1>
<div class = "buttons">
<a href="/posts">View All</a>
  <%= link_to "Add New", new_post_path %>
</div>
<% @recent_posts.each do |post| %>
<div class = "post">
      <h2><%=link_to post.title, post%></h2>
</div>
<%end%>

scribble/app/views/welcome/index.html.erb
<%= link_to 'My Blog', controller: 'posts' %>